spring:
  docker:
    compose:
      enabled: false
  datasource:
    url: jdbc:mysql://lxp-mysql:3306/lxp_content_stag?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
  data:
    redis:
      host: redis
      port: 6379
      password: ${SPRING_DATA_REDIS_PASSWORD}
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}

services:
  user:
    url: http://lxp-user:8080

passport:
  key:
    secret-key: ${PASSPORT_SECRET}