spring:
  docker:
    compose:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3308/lxp_content?sslMode=DISABLED&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: lxp
    password: lxp
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: lxp
    password: lxp

services:
  user:
    url: http://localhost:8081

passport:
  key:
    secret-key: local-secret-key-for-testing-minimum-32chars